---
title: "bretsAnalysis"
output: html_document
---

Team goal: Predict Global Videogame Sales based off of given 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rpart)
library(rpart.plot)
library(maptree)
source("https://raw.githubusercontent.com/grbruns/cst383/master/lin-regr-util.R")
cross_validate_lm = function(dat, y, xs, n=10) {
  # create the formula to be used with lm
  ff = reformulate(xs, y)
  
  # compute indexes of the groups
  k = nrow(dat)  
  dat1 = dat[sample(1:k),]     # shuffle the data
  starts = seq(1, k, by=floor(k/n))[1:n]
  ends = c(starts[2:n]-1, k)
  
  sum_rmse = 0
  for (i in 1:n) {
    tests = starts[i]:ends[i]
    fit = lm(ff, data=dat1[-tests,])
    if (length(fit$coefficients) > fit$rank) {
      print(paste0("rank-deficit problem with ", ff))
    }
    predicted = predict(fit, newdata=dat1[tests,])
    actual = dat1[tests,y]
    rmse = sqrt(mean((actual-predicted)^2))
    sum_rmse = sum_rmse + rmse
    # print(paste0(i,": RMSE = ",rmse))
  }
  return(sum_rmse/n)
}

setwd('..')
dat = read.csv( paste0(getwd(), "/data/Video_Game_Sales_as_of_Jan_2017.csv"))
```

```{r}
# 7191 complet cases
set.seed(123)
dat = dat[complete.cases(dat),]

# Converting column names from uppers to lowers
names(dat) = tolower(names(dat))
```

```{r}
str(dat)
```

```{r}
split = split_data(dat, c(4,1))
tr_dat = split[[1]]
te_dat = split[[2]]
```


```{r}
fit = rpart(global_sales ~ genre + platform + user_count, data=tr_dat)
```

```{r}
prp(fit, extra=1, varlen=-10,main="Regression Tree to predict Global Sales", type = 2, tweak = 1.5, box.col="tan")
```


```{r}
predicted = predict(fit, te_dat)
errors = te_dat$global_sales - predicted
rmse = sqrt(mean(errors^2))
rmse
```



```{r}
plot_predict_actual(predicted, te_dat$global_sales, 2, "regression tree price prediction")
```


```{r}
names = c("global_sales","critic_count", "critic_score", "user_count", "user_score")
plot(dat[,names])
```

```{r}
rmse_cv = cross_validate_lm(te_dat, "global_sales", c("platform", "genre", "user_count"))
rmse_cv
```



### Linear Regression
Linear regression model built from the features of user count and user score. From our summary we see that user count and user score of ***, this in turn means they have strong relationship to global sales.
```{r}

fit2 = lm(global_sales ~ user_count * user_score, data=tr_dat)
# Summary
summary(fit2)

# Conf Mtx
#temp = predict(fit, newdata=te_dat, type="response")
#predicts = as.numeric(temp > 0.7)
#actuals = te_dat$hit
#conf_mtx = table(predicts, actuals)
#conf_mtx
```

```{r}
# Plot
predicted2 = predict(fit2, newdata=te_dat)
actual2 = te_dat$global_sales

plot(actual2 ~ predicted2, col="DARK RED", pch=20, main="Actual Global Sales by Predicted Global Sales", xlab="Predicted", ylab="Sales")
abline(a=0, b=1, col="BLUE", lty=2, lwd=2)
```


### RMSE
```{r}
errors2 = actual2-predicted2
#plot(density(errors))
hist(errors2)

# RMSE
#rmse = sqrt(mean(errors^2))
rmse2 = sqrt(mean((actual2-predicted2)^2))
rmse2
```


### Linear Regression Diagnostics
```{r}
plot(density(errors), col = "green")
lines(density(errors2), col = "blue")
```

