### Data
```{r}
library(rpart)
library(rpart.plot)
library(maptree)
setwd('..')
dat = read.csv( paste0(getwd(), "/data/Video_Game_Sales_as_of_Jan_2017.csv"))
```

```{r}
# 7191 complet cases
set.seed(123)
before = nrow(dat)

# get all the complete cases
# we retain 41% of our data and discard 59%
dat = dat[complete.cases(dat),]
after = nrow(dat)
print(after/before)

# Converting column names from uppers to lowers
names(dat) = tolower(names(dat))
str(dat)
summary(dat)

# Adding column 'hit' based off of global sales threshold of 1 mil copies sold
dat$hit = factor(ifelse(dat$global_sales>=1, 1, 0))
```


```{r}
#bottom, left, top, and rig
par(mar=c(5,6,1,1))
barplot(table(dat$genre),horiz=TRUE,las=1)
```


```{r}
# Critic Score
plot(critic_score ~ genre, data=dat, main="Critic Score by Genre", xlab="Genre", ylab="Critic Score", col="RED")
# User Score
plot(user_score ~ genre, data=dat, main="User Score by Genre", xlab="Genre", ylab="User Score", col="RED")
```

```{r}
plot(global_sales[hit==1] ~ critic_score[hit==1], data=dat, col="RED", pch=20, xlab="Critic Score", ylab="Global Sales", main="Critic Score by Global Sales")
points(global_sales[hit==0] ~ critic_score[hit==0], data=dat, col="NAVY", pch=20)
legend("topleft", col=c("RED","NAVY"), legend=c(">1MIL IN SALES", "<1MIL IN SALES"), pch=15)
```

```{r}
par(mar=c(4,9,1,3))
barplot(table(dat$hit, dat$genre), col=c("RED","NAVY"), horiz=T, las=1)
```


```{r}
par(mar=c(4,9,1,3))
barplot(sort(table(dat$platform),ascending=T),horiz=T, las=1, col="RED", main="Games per Platform")
```


### Sampling & Splitting
```{r}
# 
set.seed(123)

# 70% and 30% split
tr_rows = sample(nrow(dat), 0.7 * nrow(dat))
tr_dat = dat[tr_rows,] # training data
te_dat = dat[-tr_rows,] # test data
```


### Logistic Regression
```{r}
#dat$hit = as.numeric(dat$hit)

# predicting hit, using predictor global_sales, platform and critic_score
fit = glm(hit ~ global_sales + platform + critic_score, family=binomial(), data=tr_dat)

# Summary
summary(fit)

# Confusion Matrix
temp = predict(fit, newdata=te_dat, type="response")
predicts = as.numeric(temp > 0.7)
actuals = te_dat$hit
conf_mtx = table(predicts, actuals)
conf_mtx



fit = glm(hit ~ global_sales + platform + critic_score, family=binomial(), data=tr_dat)

# Summary
summary(fit)

# Confusion Matrix
temp = predict(fit, newdata=te_dat, type="response")
predicts = as.numeric(temp > 0.7)
actuals = te_dat$hit
conf_mtx = table(predicts, actuals)
conf_mtx


```

```{r}
# Success Rate
succ_rate = mean(predicts == actuals)
succ_rate
```

```{r}

# Is there a certain Devloper/publisher that sell the most


publishedGamesByPublish = table(dat$publisher )
publishedGamesByPublish = publishedGamesByPublish[publishedGamesByPublish > 0]
publishedGamesByPublish = sort(publishedGamesByPublish,decreasing=TRUE)
#bottom, left, top, and rig
par(mar=c(5,15,1,1))
barplot(head(publishedGamesByPublish,10),horiz=TRUE,las=1,main="Top 10 Publishers with the most games")
```


Some more ideas to explore. 
  - Number of games per platform to find out which platform has the most games.
  - Does a certain genre sell more than others
  - Developers/publishers that produce the most games
  - Is there a certain Devloper/publisher that sell the most


